import Image from "next/image";
import Link from "next/link";

import { cn } from "@/lib/utils";

/**
 * The National Plasto brand mark.
 *
 * Two files, because the supplied artwork is dark ink and would vanish on a
 * dark surface:
 *
 *   national-plasto.png       dark ink — for light surfaces
 *   national-plasto-dark.png  cream wordmark, blue arc and red script kept —
 *                             generated by scripts/make-dark-logo.py
 *
 * The swap is done in **CSS**, not JavaScript. Both files are in the markup and
 * `dark:` decides which one is visible, so the correct mark is painted on the
 * very first frame — no `mounted` check, no hydration mismatch, and no flash of
 * the wrong logo before React starts. The cost is one extra image request; both
 * are small (36 KB and 21 KB) and the browser caches them for the whole session.
 *
 * Surfaces come in two kinds:
 *
 *   default    an ordinary surface that follows the theme (header, auth pages,
 *              mobile drawer, 404) — light mark in light mode, dark mark in dark
 *   onBrand    an always-navy brand surface (footer, admin sidebar, admin
 *              login) — these use `bg-brand`, which deliberately does NOT invert
 *              with the theme, so the reversed-out mark is correct in both
 */

const LIGHT_SRC = "/logo/national-plasto.png";
const DARK_SRC = "/logo/national-plasto-dark.png";
const LOGO_W = 486;
const LOGO_H = 236;

export function Logo({
  className,
  href = "/",
  compact = false,
  onBrand = false,
  priority = false,
}: {
  className?: string;
  href?: string | null;
  /** Renders the mark smaller, for tight headers. */
  compact?: boolean;
  /** True on always-dark brand surfaces — see the note above. */
  onBrand?: boolean;
  /** Only the header instance should preload; the rest are below the fold. */
  priority?: boolean;
}) {
  const sizeClass = compact ? "h-8" : "h-10 sm:h-11";
  const common = "w-auto object-contain";

  const mark = (
    <span className={cn("flex items-center", className)}>
      {onBrand ? (
        <Image
          src={DARK_SRC}
          width={LOGO_W}
          height={LOGO_H}
          alt="National Plasto Pvt. Ltd."
          priority={priority}
          sizes="220px"
          className={cn(common, sizeClass)}
        />
      ) : (
        <>
          <Image
            src={LIGHT_SRC}
            width={LOGO_W}
            height={LOGO_H}
            alt="National Plasto Pvt. Ltd."
            priority={priority}
            sizes="220px"
            className={cn(common, sizeClass, "block dark:hidden")}
          />
          {/* Decorative duplicate: the alt text above already names the brand,
              so announcing it twice would just be noise for a screen reader. */}
          <Image
            src={DARK_SRC}
            width={LOGO_W}
            height={LOGO_H}
            alt=""
            aria-hidden
            priority={priority}
            sizes="220px"
            className={cn(common, sizeClass, "hidden dark:block")}
          />
        </>
      )}
    </span>
  );

  if (!href) return mark;

  return (
    <Link href={href} aria-label="National Plasto — home" className="shrink-0">
      {mark}
    </Link>
  );
}

/**
 * The NEXT sub-brand lockup ("From the House of NEXT").
 *
 * Kept separate from `Logo` so a collection mark and the corporate mark can
 * never be mistaken for one another.
 */
const NEXT_LIGHT_SRC = "/logo/next-nppl.png";
const NEXT_DARK_SRC = "/logo/next-nppl-dark.png";

export function NextBrandLogo({
  className,
  onBrand = false,
}: {
  className?: string;
  /** True on an always-dark surface. */
  onBrand?: boolean;
}) {
  if (onBrand) {
    return (
      <Image
        src={NEXT_DARK_SRC}
        width={444}
        height={204}
        alt="NEXT — from the house of National Plasto"
        priority
        sizes="180px"
        className={cn("h-9 w-auto object-contain shrink-0", className)}
      />
    );
  }

  return (
    <span className={cn("inline-flex items-center shrink-0", className)}>
      <Image
        src={NEXT_LIGHT_SRC}
        width={444}
        height={204}
        alt="NEXT — from the house of National Plasto"
        priority
        sizes="180px"
        className="h-full w-auto object-contain shrink-0 block dark:hidden"
      />
      <Image
        src={NEXT_DARK_SRC}
        width={444}
        height={204}
        alt=""
        aria-hidden
        priority
        sizes="180px"
        className="h-full w-auto object-contain shrink-0 hidden dark:block"
      />
    </span>
  );
}
